export const ArcadeTableTag = 'ArcadeTable'
export const BallTag = 'Ball'
export const BarrierTag = 'Barrier'
export const BouncerTag = 'Bouncer'
export const DrainTag = 'Drain'
export const MaterializerTag = 'Materializer'
export const ScorerTag = 'Scorer'
export const SeatTag = 'Seat'
