-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		gui = {
			blur = "rbxassetid://15647717080",
			button_glow_top = "rbxassetid://15653047065",
			vignette = "rbxassetid://15647717200",
		},
	},
}