name: Release Beta

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

concurrency:
  group: beta_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone state
        uses: actions/checkout@v2
        with:
          path: state
          repository: GreenAppers/state
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

      - name: Setup Node.JS
        uses: bahmutov/npm-install@v1

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: yarn build

      - name: Upload place artifact
        uses: actions/upload-artifact@v3
        with:
          name: place
          path: SurviveArcade.rbxlx

      - name: Deploy game
        run: |
          cp state/SurviveArcade/.mantle-state.yml .
          mantle deploy --environment beta
          cp .mantle-state.yml state/SurviveArcade
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}

      - name: Update state if changed
        uses: cpina/github-action-push-to-another-repository@main
        if: always()
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        with:
          source-directory: 'state'
          destination-github-username: 'GreenAppers'
          destination-repository-name: 'state'
          user-email: GreenAppers@gmail.com
          target-branch: main
